name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

env:
  IMAGE_NAME: kubedeploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        env:
          CI_VERSION: ${{ github.ref }}
        run: sbt "; test; assembly"

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME" --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')
          # Set version to commit hash
          VERSION="${GITHUB_SHA::8}"
          echo "$IMAGE_ID:$VERSION"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:$VERSION"